# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tb
  fp16_no_flatten_grads: true

checkpoint:
  save_interval: 1
  save_interval_updates: 10000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: accuracy
  maximize_best_checkpoint_metric: true

task:
  _name: mae_image_classification
  data: /workspace

dataset:
  num_workers: 6
  batch_size: 256
  skip_invalid_size_inputs_valid_test: true
  required_batch_size_multiple: 1
  valid_subset: val

distributed_training:
  distributed_world_size: 1
  nprocs_per_node: 1
  distributed_port: -1

criterion:
  _name: model
  log_keys:
    - correct

optimization:
  max_update: 50_000
  lr: [0.001]

optimizer:
  _name: composite
  dynamic_groups: true
  groups:
    default:
      lr_float: 0.001
      optimizer:
        _name: adam
        adam_betas: [0.9,0.95]
        weight_decay: 0.05
      lr_scheduler:
        _name: cosine
        warmup_updates: 3200 # round(50_000*16_000/250_200, 2) -> calculate number of warmup steps based on percentage of d2v
        min_lr: 1e-6

lr_scheduler: pass_through

model:
  _name: mm_data2vec_image_classification
  mixup: 0.7
  mixup_prob: 0.9

  model_path: ???
